// Copyright 2024 Igor Molchanov. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v19.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum VarioqubFetchErrorPigeon: Int {
  case emptyResult = 0
  case identifiersNull = 1
  case responseParseError = 2
  case requestThrottled = 3
  case networkError = 4
  case internalError = 5
}

/// Generated class from Pigeon that represents data sent in messages.
struct VarioqubSettingsPigeon {
  var clientId: String
  var url: String? = nil
  var fetchThrottleIntervalMs: Int64? = nil
  var logs: Bool? = nil
  var activateEvent: Bool? = nil
  var trackingWithAppMetrica: Bool
  var clientFeatures: [String?: String?]

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> VarioqubSettingsPigeon? {
    let clientId = __pigeon_list[0] as! String
    let url: String? = nilOrValue(__pigeon_list[1])
    let fetchThrottleIntervalMs: Int64? = isNullish(__pigeon_list[2]) ? nil : (__pigeon_list[2] is Int64? ? __pigeon_list[2] as! Int64? : Int64(__pigeon_list[2] as! Int32))
    let logs: Bool? = nilOrValue(__pigeon_list[3])
    let activateEvent: Bool? = nilOrValue(__pigeon_list[4])
    let trackingWithAppMetrica = __pigeon_list[5] as! Bool
    let clientFeatures = __pigeon_list[6] as! [String?: String?]

    return VarioqubSettingsPigeon(
      clientId: clientId,
      url: url,
      fetchThrottleIntervalMs: fetchThrottleIntervalMs,
      logs: logs,
      activateEvent: activateEvent,
      trackingWithAppMetrica: trackingWithAppMetrica,
      clientFeatures: clientFeatures
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      url,
      fetchThrottleIntervalMs,
      logs,
      activateEvent,
      trackingWithAppMetrica,
      clientFeatures,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FetchErrorPigeon {
  var message: String? = nil
  var error: VarioqubFetchErrorPigeon

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> FetchErrorPigeon? {
    let message: String? = nilOrValue(__pigeon_list[0])
    let error = VarioqubFetchErrorPigeon(rawValue: __pigeon_list[1] as! Int)!

    return FetchErrorPigeon(
      message: message,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      message,
      error.rawValue,
    ]
  }
}

private class VarioqubApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return FetchErrorPigeon.fromList(self.readValue() as! [Any?])
    case 129:
      return VarioqubSettingsPigeon.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VarioqubApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FetchErrorPigeon {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? VarioqubSettingsPigeon {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VarioqubApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VarioqubApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VarioqubApiPigeonCodecWriter(data: data)
  }
}

class VarioqubApiPigeonCodec: FlutterStandardMessageCodec {
  static let shared = VarioqubApiPigeonCodec(readerWriter: VarioqubApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VarioqubApiPigeon {
  func build(settings: VarioqubSettingsPigeon) throws
  func fetchConfig(completion: @escaping (Result<FetchErrorPigeon?, Error>) -> Void)
  func activateConfig(completion: @escaping (Result<Void, Error>) -> Void)
  func getString(key: String, defaultValue: String) throws -> String
  func getBool(key: String, defaultValue: Bool) throws -> Bool
  func getInt(key: String, defaultValue: Int64) throws -> Int64
  func getDouble(key: String, defaultValue: Double) throws -> Double
  func getId() throws -> String
  func getAllKeys() throws -> [String]
  func getAllValues() throws -> [String: String]
  func setDefaults(values: [String: Any]) throws
  func putClientFeature(key: String, value: String) throws
  func clearClientFeatures() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VarioqubApiPigeonSetup {
  /// The codec used by VarioqubApiPigeon.
  static var codec: FlutterStandardMessageCodec { VarioqubApiPigeonCodec.shared }
  /// Sets up an instance of `VarioqubApiPigeon` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VarioqubApiPigeon?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let buildChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.build\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      buildChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! VarioqubSettingsPigeon
        do {
          try api.build(settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      buildChannel.setMessageHandler(nil)
    }
    let fetchConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.fetchConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchConfigChannel.setMessageHandler { _, reply in
        api.fetchConfig { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchConfigChannel.setMessageHandler(nil)
    }
    let activateConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.activateConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activateConfigChannel.setMessageHandler { _, reply in
        api.activateConfig { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      activateConfigChannel.setMessageHandler(nil)
    }
    let getStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.getString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let defaultValueArg = args[1] as! String
        do {
          let result = try api.getString(key: keyArg, defaultValue: defaultValueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStringChannel.setMessageHandler(nil)
    }
    let getBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.getBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let defaultValueArg = args[1] as! Bool
        do {
          let result = try api.getBool(key: keyArg, defaultValue: defaultValueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBoolChannel.setMessageHandler(nil)
    }
    let getIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.getInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let defaultValueArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        do {
          let result = try api.getInt(key: keyArg, defaultValue: defaultValueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getIntChannel.setMessageHandler(nil)
    }
    let getDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.getDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let defaultValueArg = args[1] as! Double
        do {
          let result = try api.getDouble(key: keyArg, defaultValue: defaultValueArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDoubleChannel.setMessageHandler(nil)
    }
    let getIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.getId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getIdChannel.setMessageHandler(nil)
    }
    let getAllKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.getAllKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllKeysChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllKeys()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllKeysChannel.setMessageHandler(nil)
    }
    let getAllValuesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.getAllValues\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllValuesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllValues()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllValuesChannel.setMessageHandler(nil)
    }
    let setDefaultsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.setDefaults\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDefaultsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valuesArg = args[0] as! [String: Any]
        do {
          try api.setDefaults(values: valuesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDefaultsChannel.setMessageHandler(nil)
    }
    let putClientFeatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.putClientFeature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      putClientFeatureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        do {
          try api.putClientFeature(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      putClientFeatureChannel.setMessageHandler(nil)
    }
    let clearClientFeaturesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.varioqub_configs.VarioqubApiPigeon.clearClientFeatures\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearClientFeaturesChannel.setMessageHandler { _, reply in
        do {
          try api.clearClientFeatures()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearClientFeaturesChannel.setMessageHandler(nil)
    }
  }
}
