name: varioqub_configs
description: "Flutter plugin providing work with remote configs, experiments and A/B testing via Varioqub"
version: 0.7.0
repository: https://github.com/meg4cyberc4t/varioqub_configs
homepage: https://github.com/meg4cyberc4t/varioqub_configs
issue_tracker: https://github.com/meg4cyberc4t/varioqub_configs/issues
topics: ["varioqub", "configs", "experiments"]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^17.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.meg4cyberc4t.varioqub_configs
        pluginClass: VarioqubConfigsPlugin
      ios:
        pluginClass: VarioqubConfigsPlugin
