name: varioqub_configs
description: " Flutter plugin providing work with remote configs, experiments and A/B testing via Varioqub"
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^16.0.5

flutter:
  plugin:
    platforms:
      android:
        package: com.meg4cyberc4t.varioqub_configs
        pluginClass: VarioqubConfigsPlugin
      ios:
        pluginClass: VarioqubConfigsPlugin